version: '3.8'

services:
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - "5432:5432"
    env_file:
      - .development.env
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}